import { h, Component } from 'preact';
import { Link } from 'preact-router';
import style from './style';

export default class Impressum extends Component {
	componentDidMount() {
		window.scrollTo(0, 0);
	}
	render() {
		return (
			<div>
				<p>Impressum</p>
				<p>Angaben gemäß §5TMG:</p>
				<p>Verantwortlich für den Inhalt:</p>
				<p>Autopflege Mieth<br />
				Inhaber Marvin Mieth<br />
				Bussardstr. 22<br />
				46282 Dorsten</p>
				<p>Standort Halle: Marienstr. 41
				46284 Dorsten</p>
				<p>Kontaktaufnahme bitte ausschließlich per eMail!
				eMail: <a href="mailto:mmieth+autopflege@gmail.com">mmieth+autopflege [at] gmail.com</a></p>
				<p><small>Mobil: 0170 32 62 412</small></p>
				<p>Haftungsausschluss:</p>
				<p>Haftung für Inhalte</p>
				<p>Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
				<p>Haftung für Links</p>
				<p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>

				<p>Urheberrecht</p>

				<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>

				<p>Datenschutz</p>

				<p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.</p>

				<p>Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p>

				<p>Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.</p>

				<p>Datenschutzerklärung für die Nutzung von Facebook-Plugins (Like-Button)</p>

				<p>Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder dem “Like-Button” (“Gefällt mir”) auf unserer Seite. Eine Übersicht über die Facebook-Plugins finden Sie hier: http://developers.facebook.com/docs/plugins/.
				Wenn Sie unsere Seiten besuchen, wird über das Plugin eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Wenn Sie den Facebook “Like-Button” anklicken während Sie in Ihrem Facebook-Account eingeloggt sind, können Sie die Inhalte unserer Seiten auf Ihrem Facebook-Profil verlinken. Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von facebook unter http://de-de.facebook.com/policy.php</p>

				<p>Wenn Sie nicht wünschen, dass Facebook den Besuch unserer Seiten Ihrem Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem Facebook-Benutzerkonto aus.</p>

				<p>Datenschutzerklärung für die Nutzung von Google Analytics</p>

				<p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. (“Google”). Google Analytics verwendet sog. “Cookies”, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.
				Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: http://tools.google.com/dlpage/gaoptout?hl=de.</p>

				<p>Datenschutzerklärung für die Nutzung von Twitter</p>

				<p>Auf unseren Seiten sind Funktionen des Dienstes Twitter eingebunden. Diese Funktionen werden angeboten durch die Twitter Inc., 795 Folsom St., Suite 600, San Francisco, CA 94107, USA. Durch das Benutzen von Twitter und der Funktion “Re-Tweet” werden die von Ihnen besuchten Webseiten mit Ihrem Twitter-Account verknüpft und anderen Nutzern bekannt gegeben. Dabei werden auch Daten an Twitter übertragen.</p>

				<p>Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Twitter erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von Twitter unter http://twitter.com/privacy.</p>

				<p>Ihre Datenschutzeinstellungen bei Twitter können Sie in den Konto-Einstellungen unterhttp://twitter.com/account/settings ändern.</p>

				<p>AGB
				Alle zwischen „Autopflege Mieth“ (im folgenden Anbieter genannt) und den Kunden (im folgenden Auftraggeber genannt) abgeschlossenen Verträge liegen folgende Allgemeine Geschäftsbedingungen (im folgenden AGB genannt) zugrunde: §1 Geltungsbereich der Allgemeinen GeschäftsbedingungenFür alle zwischen dem Anbieter und dem Auftraggeber abgeschlossenen Verträge gelten unsere AGB. Zu diesen zählen Geschäftsbereiche wie Fahrzeugaufbereitung, Fahrzeugwäsche, etc. 1.1. Alle Vereinbarungen, die von unseren AGB abweichen bedürfen der Schriftform. Von unseren AGB abweichende Vereinbarungen nehmen keinen Einfluss auf die Gültigkeit der übrigen Bedingungen. 1.2. Änderungen an den AGB sind vorbehalten und müssen einen Monat vor Wirksamkeit schriftlich angekündigt werden. 1.3. Wenn eine oder mehrere Klauseln bzw. Absätze unwirksam sind, so bleiben die restlichen Klauseln und Absätze der AGB weiterhin gültig.</p>

				<p>§2 Terminvereinbarungen 2.1. Terminvereinbarungen werden im rechtlichen Sinne als Auftragserteilung behandelt und werden als solche anerkannt. Vor Durchführung der Fahrzeugreinigung/-aufbereitung muss der Auftraggeber ein schriftliches Auftragsformular unterzeichnen oder alternativ dem Webbasierten Auftragskonfigurator zustimmen, wo alle relevanten Daten aufgenommen und gespeichert werden. Dieses ist unabhängig von der Terminvereinbarung. 2.2. Terminvereinbarungen werden mit Einverständnis von Auftraggeber und Anbieter getroffen. Eilaufträge müssen vom Auftraggeber als solche vor Auftragsannahme deklariert werden. Eine Auftragsannahme von Eilaufträgen behält sich der Anbieter vor, da diese sich nach der Auftragslage richtet.</p>

				<p>§3 Nichteinhaltung von Terminvereinbarungen 3.1. Die Gültigkeit von Terminvereinbarungen besteht bis zum vereinbarten Termin, sofern nicht mindestens zwei Werktage vorher von einer Seite der Geschäftsparteien aufgekündigt wird. 3.2. Sofern kein erkennbarer Grund für die Nichteinhaltung eines Termins erkennbar ist, kann der Anbieter eine Kostenpauschale in Höhe von 20% des vereinbarten Preises in Rechnung stellen, bzw. geltend machen. 3.3. Das Fahrzeug sollte bei Übergabe keine losen Teile aufweisen. Wertsachen oder andere Gegenstände müssen vorher entfernt werden. Es können keine Schadenersatzansprüche gegen den Anbieter und dessen Mitarbeiter bei fehlenden oder nicht zum Fahrzeug gehörenden Teilen oder Wertsachen geltend gemacht werden.</p>

				<p>§4 Reklamationen 4.1. Die durchgeführten Leistungen des Anbieters werden zusammen mit dem Auftraggeber bei Übergabe des Fahrzeuges überprüft. Reklamationen können ausschließlich nur nach erbrachter Leistung geltend gemacht werden. Der Anbieter hat das ausdrückliche Recht zur Nachbesserung, sofern die Reklamation berechtigt ist. 4.2. Reklamationen sind vom Geschädigten vor Ort und unverzüglich im Beisein des Anbieters schriftlich festzuhalten. 4.3. Reklamationen, die sich auf eine Beschädigung am Fahrzeug durch den Anbieter beziehen bzw. verursacht sein könnten, müssen unverzüglich fotografisch dokumentiert werden. Anderweitig ist eine Anerkennung der Reklamation nicht möglich.</p>

				<p>§5 Haftung und Garantie 5.1. Schadenersatzansprüche seitens des Auftraggebers können nur geltend gemacht werden, wenn dem Anbieter oder einem seiner Mitarbeiter grobe Fahrlässigkeit oder Vorsatz angelastet werden kann. 5.2. Bei Lackschäden, die durch den Anbieter verursacht werden und ihren Ursprung in schadhaften Lacken haben, wie z.B. durch Steinschlag, Lackabplatzungen, schlecht verarbeiteten Lacken, Kratzer, etc., können keine Schadenersatzansprüche gegen den Anbieter und dessen Mitarbeiter geltend gemacht werden. 5.3. Bei stark verschmutzten Innenausstattungen, die Flecken oder Blessuren aufweisen, können leicht aggressive Chemikalien eingesetzt werden. Dies kann zu Farbverblassungen und -abweichungen führen. Der Auftraggeber muss vor der Unterzeichung des Auftragformulars hierüber informiert werden. Wird eine Durchführung dieser Arbeiten dennoch gewünscht, wird durch seine Unterschrift auf dem Auftragsformular jegliche diesbezügliche Haftung seitens des Anbieters ausgeschlossen. 5.4. Die Haftung für alle Schäden am Fahrzeug, die vor der Fahrzeugaufbereitung an dem betreffenden Fahrzeug vorhanden waren (z.B. Karosserieschäden, Kratzer und Dellen, schadhafte Felgen, Antennen, loses und schadhaftes Interieur oder Zubehör, welches im Vorfeld schlecht bzw. unfachmännisch angebracht wurde, etc.) oder durch die Arbeiten am Fahrzeug vergrößert wurden, wird nicht übernommen. 5.5. Motor- und Motorenraumwäsche werden nur an Kraftfahrzeugen mit einwandfreier Elektrikabdichtung durchgeführt. Mit der Auftragserteilung zur Motor- und Motorenraumwäsche bestätigt der Auftraggeber die einwandfreie Elektroabdichtung im Motorenraum seines Fahrzeugs. Bei Ausfällen übernimmt der Anbieter keinerlei Haftung. 5.6. Bei empfindlichen Elektrobauteilen (z.B. Alarmanlagen, Auto-HiFi, etc.) ist der Auftraggeber verpflichtet, diese im Vorfeld der auszuführenden Arbeiten an seinem Fahrzeug dem Anbieter zu melden bzw. dies auf dem Auftragsformular schriftlich zu vermerken.</p>

				<p>§6 Formalitäten und schriftliche Absicherung 6.1. Vor Beginn der durchzuführenden Arbeiten am Fahrzeug muss das Auftragsformular vom Auftraggeber unterzeichnet werden. Hierzu gehört ggf. eine Beschreibung der vorhandenen Schäden am Fahrzeug. Dies dient der rechtlichen Absicherung des Auftraggebers, des Anbieters sowie dessen Mitarbeiter. 6.2. Der Anbieter behält sich rechtliche Schritte gegen den Auftraggeber vor, wenn dieser Schadenersatzansprüche nach Abschluss des Auftrages geltend machen möchte, die sich auf bereits vor der Ausführung des Auftrages vorhandene Schäden beziehen. 6.3. Mit der Unterzeichnung des Formulars bestätigt der Auftraggeber dessen Richtigkeit. Zugleich werden durch die Unterzeichnung auch unsere Allgemeinen Geschäftsbedingungen (AGB) und die ggf. auf dem Auftragsformular festgehaltenen außerordentlichen Vereinbarungen akzeptiert und anerkannt. 6.4. Bei mündlichen Vereinbarungen akzeptiert der Auftraggeber nach Schlüsselübergabe unsere Allgemeinen Geschäftsbedingungen.</p>

				<p>§7 Zahlungsbedingungen / Zahlungsvereinbarungen 7.1. Unsere Leistungen erfolgen grundsätzlich gegen Barzahlung oder nach Vereinbarung auf Rechnung. 7.2. Die Zahlungsbedingung lautet: Zahlung sofort nach Erhalt der Rechnung ohne Abzug. 7.3. Nach vorheriger mündlicher Vereinbarung sind Ausnahmefälle möglich, müssen jedoch auf dem Auftragsformular schriftlich festgehalten werden, da diese sonst unwirksam werden.</p>

				<p>§8 Preise / Pauschalpreise 8.1. Die Preise des Anbieters sind im Allgemeinen abhängig vom Zustand bzw. vom Verschmutzungsgrad. Alle angegebenen Preise, sofern Sie nicht mit dem Auftraggeber abgesprochen sind, entsprechen Fahrzeugen mit normalem Verschmutzungsgrad. 8.2. Preisangaben auf Informationsunterlagen, sowie der Webseite des Anbieters dienen der Orientierung und sind unverbindlich. Der Endpreis kann je nach Fahrzeugzustand von den Orientierungspreisen abweichen. 8.3. Extreme Verschmutzungen wie z.B. Farben, Tierhaare, Fäkalien, etc., bei denen eine spezielle Behandlung erforderlich ist, kann ein Aufpreis gelten gemacht werden, welcher unabhängig von Pauschalpreisen oder Angeboten ist. Aufpreise müssen auf dem Auftragsformular schriftlich festgehalten werden. Sollten stärkere Verschmutzungen erst während der Reinigung bemerkt bzw. festgestellt werden, so ist der Auftraggeber unverzüglich darüber in Kenntnis zu setzen. Eine Auftragserteilung gegen Mehrkosten kann hierbei telefonisch erteilt werden. 8.4. Die endgültigen Preise der Reinigung bzw. Aufbereitung werden vor Beginn der Arbeiten festgelegt und auf dem Auftragsformular festgehalten bzw. vermerkt.</p>

				<p>§9 Fahrzeugüberführung 9.1. Der Anbieter bietet die Fahrzeugüberführung (Abholung und Zustellung) als Dienstleistung dem Auftraggeber an. Der Preis für die Überführung ist nicht in der Aufbereitung, Reinigung enthalten und wird vor Auftragsannahme mit dem Auftraggeber abgesprochen. 9.2. Die Abholung erfolgt ausschließlich nur von Mitarbeitern des Anbieters. Bei Abholung ist ein Übernahmeformular auszufüllen. Dieses beinhaltet Stammdaten des Auftraggebers, die durchzuführenden Tätigkeiten sowie den Gesamtpreis. Schäden am Fahrzeug sind sofort schriftlich festzuhalten. Siehe §6. Gleichzeitig dient dieses als Übernahmebestätigung für den Auftraggeber. Die Zustellung erfolgt ebenfalls durch einen Mitarbeiter des Anbieters. 9.3. Das Fahrzeug des Auftraggebers ist während der Überführung über die Betriebshaftpflichtversicherung des Anbieters versichert. Sie beginnt mit der Abholung und endet mit der Übergabe.</p>

				<p>§10 Sonstiges 10.1. Erfüllungsort ist Dorsten. 10.2. Gerichtsstand ist Dorsten. 10.3. Salvatorische Klausel Sollten ein oder mehrere Bedingungen rechtsunwirksam werden, so wird die betroffene Klausel durch eine andere, die dem angestrebten Zweck möglichst nahe kommt, ersetzt. Alle anderen Bedingungen verlieren durch die Rechtsungültigkeit ein oder mehrerer Bedingungen nicht ihre Gültigkeit. Das UN-Kaufrecht ist ausgeschlossen. Es gilt deutsches Recht.</p>
			</div>
		);
	}
}
